### ISSUE TITLE
Implement the wai ResponseFile type handling in Network.Wai.Servlet.Response.updateHttpServletResponse

### ISSUE THREAD

**Issue by jneira** [jneira/wai-servlet#1]
The main goals to provide an implementation that is efficient and takes into account the client cache and the header byte-range
Resources:
* File server using java servlets:
  * https://gist.github.com/jneira/cf33844230f1ae4c22bf4a82d28d12c0
  * http://www.nurkiewicz.com/2015/06/writing-download-server-part-ii-headers.html
* WAI related links:
  * https://github.com/yesodweb/wai/blob/master/warp/Network/Wai/Handler/Warp/Response.hs#L265-L322
  * https://github.com/yesodweb/wai/blob/master/warp/Network/Wai/Handler/Warp/File.hs
  * https://github.com/yesodweb/wai/blob/master/warp/Network/Wai/Handler/Warp/SendFile.hs
  * https://github.com/yesodweb/wai/blob/master/wai-app-static/Network/Wai/Application/Static.hs

**Comment by jneira** [comment]
An initial implementation that seems to work for basic cases is in [this branch](https://github.com/jneira/wai-servlet/tree/response-file)

**Comment by rahulmutt** [comment]
This looks awesome! I guess the best way to verify that this works is to make sure all the code paths work as intended. It would be great if you could list which code paths you've tried and which have yet to be tested.

The best way forward is probably to do a release for `wai-servlet` and wait for people to report any bugs if you at least the common code paths are working.

**Comment by jneira** [comment]
> I guess the best way to verify that this works is to make sure all the code paths work as intended. It would be great if you could list which code paths you've tried and which have yet to be tested.

Yeah, it will be the right approach.
The implementation is based on an adaptation of warp [response part for files](https://github.com/yesodweb/wai/blob/master/warp/Network/Wai/Handler/Warp/Response.hs#L265-L322) and its [module of file utilities](https://github.com/yesodweb/wai/blob/master/warp/Network/Wai/Handler/Warp/File.hs) so i hope the main part of the logic will be as correct as its warp counterpart.
Anyway i'll gather the code paths, which will be based in:
* Requests with the `head` http method, besides the `get` one
* Requests with all the headers involved: ifModifiedSince, ifUnmodifiedSince, ifRange, ...
  * Test if response headers are the expected: lastModified, contentLengh, contentRange, acceptRanges, ...

**Comment by jneira** [comment]
The new version of wai-servlet already has implemented this, it  would only be left to do tests about the different code paths either manually or automatic (tracked in #10)
