### ISSUE TITLE
Incorrect handling of request body

### ISSUE THREAD

**Issue by jneira** [jneira/wai-servlet#12]
* The example app that shows [the request body](https://github.com/jneira/wai-servlet/blob/master/src/Network/Wai/Servlet/Examples.hs#L62-L69) behaves incorrectly
* It shows incorrect additional content after the actual body request
* With the example app running doing `curl http://localhost:3000 -method post -body "hola"` i get:
`hola     Content/Type    text/plain"` instead `hola`
* It seems the handling of the body request servlet input stream [with foreign pointers](https://github.com/jneira/wai-servlet/blob/master/src/Network/Wai/Servlet/Request.hs#L183-L185) is not workinkg correctly

**Comment by jneira** [comment]
* If i do a `etlas select 0.0.9.6` before `etlas run` the request body shown is the correct one
  * The version with the correct output is `eta-0.0.9b6`.
  * The version with the incorrect one is `eta-0.7.0b1`.

**Comment by rahulmutt** [comment]
This most likely has to do with the fact that the new MemoryManager will not give you a precise length of the ByteBuffer from `getBoundedBuffer` - `buf.remaining()` will give you the size of the entire block. I will see if I can put together a PR to fix this.
