### ISSUE TITLE
httpVersion is partial

### ISSUE THREAD

**Issue by rahulmutt** [jneira/wai-servlet#13]
```haskell
httpVersion ::  (a <: ServletRequest) => a -> H.HttpVersion
httpVersion req = pureJavaWith req $ do 
  httpVer <- getProtocol
  return $ case httpVer of
    "HTTP/0.9" -> H.http09
    "HTTP/1.0" -> H.http10
    "HTTP/1.1" -> H.http11
```
This is the current definition of `httpVersion`. Is there a way to smoothly handle the situation when a newer version of HTTP is used?

**Comment by jneira** [comment]
Sorry, i had missed this issue completely. 
In fact HttpTypes.http20 already exists and i've added it to the funcion with 1c85327a
As there are no more constructors of `Network.HTTP.Types.Version.HttpVersion` i think we cant do much more
