### ISSUE TITLE
3-character endpoints aren't getting matched

### ISSUE THREAD

**Issue by rahulmutt** [jneira/wai-servlet#16]
See https://github.com/typelead/eta-fib-service/issues/1 for a concrete example.

**Comment by jneira** [comment]
Hi, i've tested wai-servlet with the example app that shows the request and the `rawPathInfo` and `pathInfo` fields of wai request seems to be correct with any path length: could be a servant specific problem?

**Comment by rahulmutt** [comment]
Given that the matching logic is on the servant side, probably. I wonder if the problem is that 3 characters triggers a subtle bug in the memory manager (potentially) that causes the data to get corrupted somewhere in between. I have some other reproducible MemoryManager bugs so I'll fix them first and see if that helps this.

**Comment by jneira** [comment]
After some test i find out that `http://localhost:9000/fibb` works!!
With this modificactions to let `/fib` path alone:
```haskell
type API = "fib" {- :> Capture "n" Int -} :> Get '[JSON] Value
....
server :: Application
server = serve api fibHandler
  where n = 5
        fibHandler
          | n >= 0
          = return $ object ["n" .= n, "fib" .= fib n]
          | otherwise = throwError $ err412 { errBody = "Precondition Failed: n >= 0" }
```
The [routing code of servant](https://hackage.haskell.org/package/servant-server-0.11/docs/src/Servant-Server-Internal-Router.html#pathRouter) is:
```haskell
runRouterEnv :: Router env -> env -> RoutingApplication
runRouterEnv router env request respond =
  case router of
    StaticRouter table ls ->
      case pathInfo request of
        []   -> runChoice ls env request respond
        -- This case is to handle trailing slashes.
        [""] -> runChoice ls env request respond
        first : rest | Just router' <- M.lookup first table
          -> let request' = request { pathInfo = rest }
             in  runRouterEnv router' env request' respond
        _ -> respond $ Fail err404
    CaptureRouter router' ->
      case pathInfo request of
        []   -> respond $ Fail err404
        -- This case is to handle trailing slashes.
        [""] -> respond $ Fail err404
        first : rest
          -> let request' = request { pathInfo = rest }
             in  runRouterEnv router' (first, env) request' respond
    CaptureAllRouter router' ->
      let segments = pathInfo request
          request' = request { pathInfo = [] }
      in runRouterEnv router' (segments, env) request' respond
    RawRouter app ->
      app env request respond
    Choice r1 r2 ->
      runChoice [runRouterEnv r1, runRouterEnv r2] env request respond
```
* the `StaticRouter` pattern matching seems starightforward
* so maybe the weird behaviour is in the `runChoice` call...

**Comment by rahulmutt** [comment]
@jneira Thanks for the analysis! So the issue is the `Capture` end point maybe? Maybe you can add some `traceShow`'s inside `servant` to peek into the relevant values to figure out why it's failing?

**Comment by jneira** [comment]
* I've reproduced the issue using only wai-servlet:
```haskell
appTest :: Application
appTest req respond = do
  body <- requestBody req
  let resp msg = responseLBS status200
                    [("Content-Type", "text/plain")] msg
  respond $ resp $ case pathInfo req of
                     ["fib"] ->  "ok"
                     _       ->  pack $ show $ pathInfo req

main = run 3000 $ appTest
```
* With this code `/fib` does not match but `["fib"]` is printed out
* `/fibb` matches and prints `ok`

**Comment by jneira** [comment]
* After some tests it turns out that the error is thrown with:
```haskell
appTest :: Application
appTest req respond = do
  body <- requestBody req
  let resp msg = responseLBS status200
                    [("Content-Type", "text/plain")] msg
  respond $ resp $ if (pi == "fib") then fib 
                   else fib
    where pi = head $ pathInfo req
          fib = toLazyByteString $ byteStringHex "fib"
```
* It prints `66696262` with `b` (ascii code 62) duplicated
* if you drop the comparation `pi == "fib"` it prints the correct hex `666962`

**Comment by rahulmutt** [comment]
So you're saying the the `==` implementation is somehow affecting the result. That could happen if we have a subtle bug in our `memcmp` implementation. Is it possible to make an even smaller test case that doesn't even involve `wai`?

**Comment by jneira** [comment]
I dont know what is the cause of that weird behaviour, i've tried to reproduce outside a wai app and i was not able to do it. The question is how a comparation with a String literal (as Text) can make printing another literal (as Bytestring) incorrectly... weird

**Comment by jneira** [comment]
* If you avoid Text comparation it works as expected so i think it should be a combination of Text compare code and use it inside wai:
```haskell
appTest :: Application
appTest req respond = do
  body <- requestBody req
  let resp msg = responseLBS status200
                    [("Content-Type", "text/plain")] msg
  let r = pi == "fib"
  respond $ resp $ if (r) then BSL.concat ["ok: ", fib] 
                   else BSL.concat ["ko: ", fib]
    where pi = T.unpack $ head $ pathInfo req
          fib = toLazyByteString $ byteString "fib"
```
* With this code `/fib` is matched and it prints `ok: fib`
* So next step should be debug text comparation code.. i'll share the debug info

**Comment by rahulmutt** [comment]
One thing you can do to track this is to dump the memory manager info and look for an anomalies. I've added some diagnostic features and an example can be found here:
https://github.com/typelead/eta/blob/master/libraries/base/java-utils/HSIConv.java#L162

You can create a helper java method that prints the diagnostics and import it into your test program.

**Comment by jneira** [comment]
Hi, debugging the example application i've detected that `eta.text.utils.Utils.memcmp` is even not called.
The decompiled code that fails is:
```java
public static class sat_sX88 extends eta.runtime.thunk.UpdatableThunk1 {
		public sat_sX88(Closure paramClosure) {
			super(paramClosure);
		}

		public final Closure thunkEnter(eta.runtime.stg.StgContext paramStgContext) {
			Closure localClosure1 = this.x1.evaluate(paramStgContext);
			if ((localClosure1 instanceof ghc_prim.ghc.types.datacons.ZMZN))
				return base.ghc.List.badHead().evaluate(paramStgContext);
			Closure localClosure2 = ((ghc_prim.ghc.types.datacons.ZC) localClosure1).x1.evaluate(paramStgContext);
			text.data.text.internal.datacons.Text localText1 = (text.data.text.internal.datacons.Text) localClosure2;
			int i = localText1.x3;
			Closure localClosure3 = ((Main.main14) Main.main14()).evaluate(paramStgContext);
			text.data.text.internal.datacons.Text localText2 = (text.data.text.internal.datacons.Text) localClosure3;
			if (i != localText2.x3)/* 19  */ return ((Main.main10) Main.main10()).evaluate(paramStgContext);
			int j = i;
			int k = localText2.x2;
			int m = localText1.x2;
			int n = eta.text.Utils.memcmp(localText1.x1, m, localText2.x1, k, j);
			int i1 = n;
			if (i1 != 0) {
				return ((Main.main10) Main.main10()).evaluate(paramStgContext);
				/*    */ }
			/* 18 */ return ((Main.main3) Main.main3()).evaluate(paramStgContext);
		}
	}
```
* the code exits cause in `i != localText2.x3` , `localText.x3` is (incorrectly) `4` and `i` is `3`

**Comment by rahulmutt** [comment]
@jneira Can you share the all the relevant stg dump files as well? This could potentially be a bug in the code generator and it will be clearer to see the error if we compare the stg code side-by-side with the decompiled Java code. 

Or share a link to a repo/branch/tag where we can build and generate the stg files ourselves and give a quick hint on how to track down the relevant closure that causes the error. 

Thanks for the awesome debugging work!

**Comment by jneira** [comment]
- I created a [gist with the stg dump and the pretty printed (and modified to make it compilable by javac) class](https://gist.github.com/jneira/f1e86704ef27b219d11af1c195460aca)
- The code to reproduce it is in [this branch](https://github.com/jneira/wai-servlet-handler-jetty/blob/debug-text/examples/Main.hs) of wai-servlet-handler-jetty

**Comment by jneira** [comment]
Could be the cause this literal `4` in the [class](https://gist.github.com/jneira/f1e86704ef27b219d11af1c195460aca#file-main-java-L162)/ [stg](https://gist.github.com/jneira/f1e86704ef27b219d11af1c195460aca#file-main-dump-stg-L475)?

**Comment by rahulmutt** [comment]
To investigate this, you need to take a close look at `Text.pack` and at the core is this function `unstream`:
```haskell
unstream :: Stream Char -> Text
unstream (Stream next0 s0 len) = runText $ \done -> do
  -- Before encoding each char we perform a buffer realloc check assuming
  -- worst case encoding size of two 16-bit units for the char. Just add an
  -- extra space to the buffer so that we do not end up reallocating even when
  -- all the chars are encoded as single unit.
  let mlen = upperBound 4 len + 1
  arr0 <- A.new mlen
  let outer !arr !maxi = encode
       where
        -- keep the common case loop as small as possible
        encode !si !di =
            case next0 si of
                Done        -> done arr di
                Skip si'    -> encode si' di
                Yield c si'
                    -- simply check for the worst case
                    | maxi < di + 1 -> realloc si di
                    | otherwise -> do
                            n <- unsafeWrite arr di c
                            encode si' (di + n)

        -- keep uncommon case separate from the common case code
        {-# NOINLINE realloc #-}
        realloc !si !di = do
            let newlen = (maxi + 1) * 2
            arr' <- A.new newlen
            A.copyM arr' 0 arr 0 di
            outer arr' (newlen - 1) si di

  outer arr0 (mlen - 1) s0 0
```
The `4` correponds to `mlen - 1` which is fine since `mlen = 4 + 1` (see the definition of `upperBound`). The problem is likely further in the code.

**Comment by rahulmutt** [comment]
> the code exits cause in i != localText2.x3 , localText.x3 is (incorrectly) 4 and i is 3
How were you able to determine this? Using a debugger?

**Comment by jneira** [comment]
Yeah, i debugged the java decompiled code in eclipse and i was able to set breakpoints and inspect the values

**Comment by rahulmutt** [comment]
Based on the information you have supplied, it seems like `T.pack` is performing an incorrect conversion, since the length is coming out as 4.

**Comment by rahulmutt** [comment]
Can you investigate what led to the 4 being set as the length of the text?

**Comment by rahulmutt** [comment]
This amounts to setting breakpoints in `Main.$wa2`.

**Comment by jneira** [comment]
It seems that the problematic code could be:
```java
public static class main16 extends eta.runtime.thunk.CAF {
		public final Closure thunkEnter(eta.runtime.stg.StgContext paramStgContext) {
			try {
				return ghc_prim.ghc.CString.unpackCStringzh(paramStgContext,
						eta.runtime.io.MemoryManager.loadStringUTF8("fib"));
			} catch (UnsupportedEncodingException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				return null;
			}
		}
	}
```
- In `$wa2` [it checks that `localClosure3` is `ghc_prim.ghc.types.datacons.ZMZN`](https://gist.github.com/jneira/f1e86704ef27b219d11af1c195460aca#file-main-java-L51) and it is iterating 4 chars before it evaluates `localObject6 == paramClosure == main16` to that value
- So the problem could be in `GHC.CString.unpackCString`?

**Comment by rahulmutt** [comment]
The recent Eta has a `toString()` implementation for all closures so you can see the raw heap layout of any Eta heap object (functions, thunks, values). Since you have control over the Java code, can you can try to add a `System.out.println()` on the result of `unpackCStringzh` and it should show you the result.

**Comment by jneira** [comment]
Good one! i was able to see the runtime values but printing it out is handy. The result is:
```
main16 closure: : (C# 102) (sat_s6YE[_] (unpack_s6Y9[1] 49472L) null)
// In $wai2 loop
localClosure3: : (C# 102) (sat_s6YE[_] (unpack_s6Y9[1] 49472L) null)
localClosure3: : (C# 105) (sat_s6YE[_] (unpack_s6Y9[1] 49472L) null)
localClosure3: : (C# 98) (sat_s6YE[_] (unpack_s6Y9[1] 49472L) null)
localClosure3: : (C# 98) (sat_s6YE[_] (unpack_s6Y9[1] 49472L) null)
localClosure3: []
```

**Comment by jneira** [comment]
If you change `"fib"` for `"fibo"`the result (correct) is:
```
main16 closure: : (C# 102) (sat_s6YE[_] (unpack_s6Y9[1] 49472L) null)
localClosure3: : (C# 102) (sat_s6YE[_] (unpack_s6Y9[1] 49472L) null)
localClosure3: : (C# 105) (sat_s6YE[_] (unpack_s6Y9[1] 49472L) null)
localClosure3: : (C# 98) (sat_s6YE[_] (unpack_s6Y9[1] 49472L) null)
localClosure3: : (C# 111) (sat_s6YE[_] (unpack_s6Y9[1] 49472L) null)
localClosure3: []
```

**Comment by rahulmutt** [comment]
Ok so before we blame `unpackStringzh`, let's make sure the bytes that are written to the MemoryManager are what we expect.

In `eta.runtime.io.MemoryManager.loadString`:
1. `import java.util.Arrays;`
2. Add a `System.out.println(Arrays.toString(bytes));` after `bytes` variable is declared.

`eta-build rts-clean` to quickly test the rts changes.

**Comment by jneira** [comment]
it is correct: `[102, 105, 98]`

**Comment by rahulmutt** [comment]
```haskell
unpackCString# :: Addr# -> [Char]
{-# NOINLINE CONLIKE unpackCString# #-}
    -- There's really no point in inlining this, ever, as the loop doesn't
    -- specialise in an interesting But it's pretty small, so there's a danger
    -- that it'll be inlined at every literal, which is a waste
unpackCString# addr
  = unpack 0#
  where
    unpack nh
      | isTrue# (ch `eqChar#` '\0'#) = []
      | True                         = C# ch : unpack (nh +# 1#)
      where
        !ch = indexCharOffAddr# addr nh
```
So the only way `unpackCString#` would proceed to add additional characters is if the byte next to `fib` in the MemoryManager's heap is not `0`. I think what we need to do is in `loadString`, allocate `bytes.length + 1` and fill in the last byte in the `bytes` array with 0. Can you try implementing this and see if it fixes it?

**Comment by jneira** [comment]
Sure! i'll try it asap
