### ISSUE TITLE
Not in scope: ‘unsafePerformJavaWith’ when attempting to build during installation

### ISSUE THREAD

**Issue by aneophyte** [jneira/wai-servlet#19]
```$ etlas install --dependencies-only
Resolving dependencies...
Configuring wai-servlet-0.1.5.0...
Building wai-servlet-0.1.5.0...
Failed to install wai-servlet-0.1.5.0
Build log ( /home/funnyusername/.etlas/logs/eta-0.7.0.2/wai-servlet-0.1.5.0-I0egAxeJrMBLj7pkRuaDXn.log ):
etlas: Entering directory '/tmp/etlas-tmp-12590'
Configuring wai-servlet-0.1.5.0...
Preprocessing library for wai-servlet-0.1.5.0..
Building library for wai-servlet-0.1.5.0..
[1 of 7] Compiling Network.Wai.Servlet.File ( src/Network/Wai/Servlet/File.hs, dist/build/Network/Wai/Servlet/File.jar )
[2 of 7] Compiling Javax.Servlet    ( src/Javax/Servlet.hs, dist/build/Javax/Servlet.jar )
[3 of 7] Compiling Network.Wai.Servlet.Settings ( src/Network/Wai/Servlet/Settings.hs, dist/build/Network/Wai/Servlet/Settings.jar )
[4 of 7] Compiling Network.Wai.Servlet.Request ( src/Network/Wai/Servlet/Request.hs, dist/build/Network/Wai/Servlet/Request.jar )

src/Network/Wai/Servlet/Request.hs:80:21:
    Not in scope: ‘unsafePerformJavaWith’
etlas: Leaving directory '/tmp/etlas-tmp-12590'
etlas: Error: some packages failed to install:
wai-servlet-0.1.5.0-I0egAxeJrMBLj7pkRuaDXn failed during the building phase.
The exception was:
ExitFailure 1
wai-servlet-handler-jetty-0.1.2.0-6kNESzjPZ1EbRxix0NIil depends on
wai-servlet-handler-jetty-0.1.2.0 which failed to install.
```

This could be linked to https://github.com/typelead/eta/pull/678, most likely unreleased
But I also do see https://github.com/jneira/wai-servlet/blob/f0e2322f3563bfae8481840bd1a3acfc6892a48e/src/Network/Wai/Servlet/Request.hs#L36-L42
which might be in place for backward compatibility?

**Comment by jneira** [comment]
@aneophyte ugh, yes, the 0.1.5.0 release wanted to be backwards compatible with the code linked and https://github.com/jneira/wai-servlet/blob/0.1.5.0/wai-servlet.cabal#L46
I'll investigate why the cpp condition didn't work.
btw could you share the versions of eta and etlas used in the install?

**Comment by jneira** [comment]
@aneophyte it was a mistake in the condition for the cpp option; it is already fixed in etlas index and it should work after an `etlas update`
sorry for the inconveniences

**Comment by aneophyte** [comment]
Here are the details:
```
$  etlas --version
etlas version 1.2.0.0
compiled using version 2.1.0.0 of the etlas-cabal library 
$  etlas exec eta -- --version
Compiler for the Eta Programming Language, version 0.7.0b2```

**Comment by jneira** [comment]
@aneophyte hi, finally i've fixed the bug and it is in master and in the 0.1.5.0 tag
To get installed the new version you should do an `etlas update` and i am afraid that maybe you will have to delete `~/etlas/packages/etlas.org/wai-servlet/0.1.5.0` to force etlas to download the fixed version

**Comment by aneophyte** [comment]
Thank you very much for the prompt fix! That definitely solved the issue.

I did, however, run into one problem.
```
src/Network/Wai/Servlet/Request.hs:91:19:
    Not in scope: ‘H.http20’
    Perhaps you meant one of these:
      ‘H.http10’ (imported from Network.HTTP.Types),
      ‘H.http09’ (imported from Network.HTTP.Types),
      ‘H.http11’ (imported from Network.HTTP.Types)
etlas: Leaving directory '/tmp/etlas-tmp-12704'
etlas: Error: some packages failed to install:
wai-servlet-0.1.5.0-I0egAxeJrMBLj7pkRuaDXn failed during the building phase.
The exception was:
ExitFailure 1
```

I managed to fix it by installing `http-types` manually. I think this needs to be mentioned as it might be something to check on.

I apologize for not including the version details earlier on. This issue can be closed now, I suppose?

**Comment by jneira** [comment]
Great! thanks for notice the http-types problem, i'll take a look to the dependency to get auto the correct one
