### ISSUE TITLE
Make a 1.1.0.0 release for Eta v0.0.9

### ISSUE THREAD

**Issue by rahulmutt** [jneira/wai-servlet#4]
Can you make a `wai-servlet-1.1.0.0` release? I just tested the servant example with Eta v0.0.9 and it's working pretty well with the changes I just made. If you can upload the new version, users can seamlessly try the example without any breakage. Thanks!

**Comment by jneira** [comment]
yeah, i'll do asap

**Comment by jneira** [comment]
mmm, it seems the change preserve backwards compatibility, so the version could be 0.0.2.0?

**Comment by rahulmutt** [comment]
Agreed, so 0.2.0.0 or 0.1.1.0 (since 0.1.0.0 is the last version).

**Comment by jneira** [comment]
oh, you are right, i'll use 0.1.1.0

**Comment by jneira** [comment]
the version already is available in the repo and https://github.com/typelead/etlas-index/tree/master/packages/wai-servlet/0.1.1.0
