### ISSUE TITLE
Incorrect handling of uris with non ascii chars

### ISSUE THREAD

**Issue by jneira** [jneira/wai-servlet#5]
Actually, wai-servlet handle incorrectly (and differently than wai) uris containing non ascii chars. For example:

* For `/caña` it gives us: `rawPathInfo = "ca%F1a"` and `pathInfo = ["ca\65533"]`
* With Wai: `rawPathInfo = "/ca%C3%B1a` and `pathInfo = ["ca\241a"]`

**Comment by rahulmutt** [comment]
Is this still relevant? And what can we do to resolve the differences?

**Comment by jneira** [comment]
Well, as far as i understand you need the correct url percent encoding to get the correct original url. It would break applications with non ascii urls.
We should review the combination between the server and the wai-servlet application handling of the url. I think the main problem is the servlet container already converts the url to a specific character set (cp-1252 in my case on windows) and the application cant access (at least directly) the direct bytes of the original request.
Wai has the raw correct value of the requested url (the utf-8 percent encoding for ñ) and it converts it to cp-1252 (241/F1 for ñ)

**Comment by jneira** [comment]
* This issue are closely related with the servlet container used to run the app
* Relevant links for jetty server:
  * https://wiki.eclipse.org/Jetty/Howto/International_Characters
  * https://github.com/eclipse/jetty.project/issues/804

**Comment by jneira** [comment]
* As jetty (at least since 9.3) uses utf-8 as default encoding for the uri (including the query string) we get the warp behaviour simply encoding strings as `utf-8` (using `Data.ByteString.UTF8.fromString`) instead `iso-8859-1` (using `Data.ByteString.Char8.pack`)
* Being the unique adapter implemented i'm gonna change the default encoding for the path and the query string to use `utf-8`
* But as you can configure the jetty version used by wai-servlet-jetty-adapter to use `iso-8859-1` (or another char encoding) or implement a jetty adapter with a old version or a  tomcat version that uses it we should allow wai-servlet to use a Settings data structure and put in it a option to choose the uri encoding
  * `Network.Wai.Servlet.Request` will use that option to choose the correct encoding

**Comment by jneira** [comment]
* Default encoding changed to `utf-8` with 86478a8

**Comment by rahulmutt** [comment]
Looks great. The only thing remaining for this issue is to detect the encoding from the servlet container and adapt that `encode` function accordingly, right?

**Comment by jneira** [comment]
That would be the ideal solution but i am afraid that wai-servlet itself is server-agnostic, only knows about servlet spec and that check is closely related with each server internal api.
So in wai-servlet it could be a setting option and adapters could check the actual server uri encoding to fill that setting (if possible) or simply let the user fill it to match server and wai encodings

**Comment by rahulmutt** [comment]
Sure, that sounds good.

**Comment by jneira** [comment]
Closed by #18
