### ISSUE TITLE
Implement sendFile using java NIO

### ISSUE THREAD

**Issue by rahulmutt** [jneira/wai-servlet#8]
The new Java NIO channels API provides a very efficient way to transfer data avoiding copying through an intermediate buffer. The `sendFile` java method used through FFI should be implemented using `transferTo` or `transferFrom`, with care for Windows:

https://stackoverflow.com/questions/7379469/filechannel-transferto-for-large-file-in-windows

**Comment by jneira** [comment]
Hi, i was reading some so questions about the topic and it seems that being the destination a `ServletOutputStream`, using channels would be not as useful as when you copy between files.  
- https://stackoverflow.com/a/4652647/49554
- https://stackoverflow.com/questions/9668069/can-i-call-an-underlying-nio-channel-for-a-response-in-jetty-web-app
- https://stackoverflow.com/questions/39802643/java-async-in-servlet-3-0-vs-nio-in-servlet-3-1
- https://blogs.oracle.com/arungupta/non-blocking-io-using-servlet-31:-scalable-applications-using-java-ee-7-totd-188

Although if there were a way to get a `SocketChannel` instead a `ServletOutputStream`... i'll investigate it

**Comment by jneira** [comment]
It seems you could use java.nio to write the file to the servlet response using internal classes of jetty (i guess we could use internals of last versions of tomcat). 
* Following the [code of jetty default servlet](http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/jetty-servlet/src/main/java/org/eclipse/jetty/servlet/DefaultServlet.java?h=jetty-9.4.x-Feature#n875) 
* But wai-servlet only knows about servlet spec
  * So we could implement the write with java.nio using server specific classes and a way to "plug in" that behaviour in wai-servlet, using callbacks in Settings (or type classes?)

**Comment by rahulmutt** [comment]
Hmm using internals sounds like a maintenance nightmare. I think we should make it so that if a particular backend supports response channels, we should be able to use `transfer*` to perform the direct copy for files.

**Comment by jneira** [comment]
With #18 client code can parametrize how the file is downloaded, overriding the default behavior using java.io
So i am going to close this one and open another one in wai-servlet-jetty-adapter to track the concrete impl using java.nio
